### ISSUE TITLE
Add Login URL

### ISSUE THREAD

**Issue by GBS-Skile** [team-crescendo/laravel-forte#24]
**Is your feature request related to a problem? Please describe.**
User Table에 password라는 필드가 있는데 Create할 때는 필수적으로 입력하게 해놓고서 정작 아무데서도 안 쓰이고 있었네요! 사실 초기 계획에서는 프론트엔드 홈페이지와 연동할 때 쓰려고 만들어둔 필드였는데, 홈페이지와는 독립적으로 백엔드를 개발하기로 결정하면서 흐지부지된 기능이었어요. (디스코드 봇 안에서 상점 기능을 구현한다면, 굳이 사용자에게 비밀번호를 요구할 필요 없이 사용자의 디코 ID로 인증을 대체할 수 있기 때문)

그래도 User.password를 2차 비밀번호 같은 느낌으로 쓰면 괜찮겠다 싶어서 새로운 뷰를 파는 건 어떨지 제안해봅니다. (디스코드 봇에서 디코 ID를 검증해서 1차 인증 - 사용자한테 비밀번호를 입력받아 2차 인증 - 인증이 끝난 뒤 상점 링크 발급)

**Describe the solution you'd like**
`GET /users/{userId}/login`라는 새로운 뷰를 만들면 좋을 것 같습니다.
* parameter로 `password`를 받음
* DB에 등록된 password와...
  - 일치하면 204 No Content로 반응
  - 일치하지 않으면 403 Forbidden으로 반응

**Describe alternatives you've considered**
1. 아니면 토큰을 발급받는 `GET /users/{userId}/xsolla/token` 에서 parameter로 `password`를 추가로 입력받아 URL을 발급하기 전에 인증을 진행하는 것도 괜찮을 것 같아요
2. 사실 그냥 User 모델에서 password 필드를 빼버려도 큰 지장은 없을 것 같습니다

**Comment by getsolaris** [comment]
1번으로 할게요 ~!

**Comment by getsolaris** [comment]
생각 해보니 뷰를 만들어서 진행 하는게 좋을것 같네요.
