### ISSUE TITLE
엑솔라 웹훅 payment 오류

### ISSUE THREAD

**Issue by GBS-Skile** [team-crescendo/laravel-forte#33]
**Describe the bug**
유효한 카드 번호, username을 입력해서 현금으로 상품/포인트를 구매(payment)하려 하는 상황에서 문제가 발생함.

**To Reproduce**
https://github.com/team-crescendo/laravel-forte/commit/b75df83ded73f7804efb3d68930ea3b0374becf7#r34114965

**Comment by getsolaris** [comment]
[fix commit](https://github.com/team-crescendo/laravel-forte/commit/5022891b4226e52f97fbbda070de9910923815d5)
