### ISSUE TITLE
users.name should not be unique

### ISSUE THREAD

**Issue by GBS-Skile** [team-crescendo/laravel-forte#66]
### 이슈 설명
현재 DB에서는 users.name에 unique 조건이 붙어있는데 (`UserRegisterFormRequest` 등 참고) `Socialite::with('discord')->user()`로 넘어오는 [Discord User Object](https://discordapp.com/developers/docs/resources/user#user-object)의 `username` 필드는 uniqueness가 보장되지 않습니다.

따라서 흔한 닉네임을 보유하고 있는 Discord 사용자의 경우 해당 uniqueness 조건에 걸려 가입에 실패할 가능성이 있습니다. OAuth2를 도입한 이상 레코드의 유일성 보장은 users.email 필드만으로도 충분하다 보므로 해당 필드에 대한 unique 조건을 삭제하는 게 좋을 것 같습니다.

**Comment by MineMy** [comment]
Discord에서 users.name은 중복이 가능하고, 변경할 수도 있기 때문에 적합하지 않습니다.
또한, users.email은 이메일 등록을 안 한 사용자(NULL)나 다중 계정에서도 동일한 이메일 인증이 가능(not uniqueness)하기 때문에 적합하지 않다고 봅니다.

따라서 users.name 필드와 users.email 필드는 unique 조건을 제거하고, users.email 필드는 null값을 허용해야 한다고 생각합니다.

**Comment by return0927** [comment]
Uniqueness를 따지려면 Discord API 상의 user.id로 처리하는게 좋지 않을까요? 각 User를 Specify해야하는데 Nullable한 값은 위험하다 생각합니다.

**Comment by kang-heewon** [comment]
혹시 강희원#5303 이형태의 닉네임도 중복되나요?

**Comment by MineMy** [comment]
Discord Nitro의 경우에는 users.discriminator 까지 변경이 가능합니다. 따라서 멘션 형태의 닉네임도 부적절하다고 봅니다.
